### ISSUE TITLE
Xoá loại độc giả

### ISSUE THREAD

**Issue by pdt1804** [pdt1804/CNPM#153]

**Comment by pdt1804** [comment]
![image](https://github.com/pdt1804/CNPM/assets/128351905/4d483097-8851-48c0-b931-e61622588db8)
![image](https://github.com/pdt1804/CNPM/assets/128351905/ba6a1d28-ac49-4708-ad94-5599aa2762cd)

**Comment by SONLE03** [comment]
Thực hiện thay đổi:
 [1] Xóa bỏ button "delete" tại form "Sửa loại độc giả"
 [2] Thêm Icon "delete" tại UserControl "Loại độc giả" và thực hiện chức năng xóa trực tiếp tại UC

**Comment by SONLE03** [comment]
Commit: [https://github.com/pdt1804/CNPM/commit/081dd54495e96ed1d46bc7affc38cd3a21296d3c](url)
