### ISSUE TITLE
Sửa lỗi hiển thị độc giả ra datagridview

### ISSUE THREAD

**Issue by pdt1804** [pdt1804/CNPM#80]

**Comment by SONLE03** [comment]
Đã fix một số lỗi hiển thị của datagridview trên form độc giả

[https://github.com/pdt1804/CNPM/commit/84257eedc60b3ed6631998c31adef83204c5c401](url)

![image](https://github.com/pdt1804/CNPM/assets/92604333/dd639003-5a21-4bf2-bf47-426e1e31f60d)
